version: '3.4'

services:
  flaskapp:
    container_name: nlp-services
    image: flaskapp
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: ["sh", "-c", "python -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002"]
    ports:
      - 127.0.0.1:5010:80
    environment:
      - FLASK_APP=main.py
        #    volumes:
        #      - ./app/static/:/app/app/static

